timeout: 3

default_entry: 1
interface_branding: PyramydOS Boot Menu
interface_branding_color: 6

verbose: yes

editor_enabled: yes

/PyramydOS
    protocol: limine
    path: boot():/boot/pyramyd/pyrakrnl

    resolution: 0x0x0

    video_mode: preferred

    kaslr: no

    cmdline: haiii
